### ISSUE TITLE
EVCO2 is not working

### ISSUE THREAD

**Issue by dpolitak** [Horizon-LEAD/lead-platform-doc#10]
evco2-test-dp simulation and log is below:

Error during the model execution.

bf048245faa1
*** Reading local file: /opt/airflow/logs/dag_id=evco2_u1/run_id=manual__2023-03-28T14:30:49.312232+00:00/task_id=evco2_1_0_0_u1_11_11/attempt=1.log
[2023-03-28 14:30:52,888] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: evco2_u1.evco2_1_0_0_u1_11_11 manual__2023-03-28T14:30:49.312232+00:00 [queued]>
[2023-03-28 14:30:52,895] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: evco2_u1.evco2_1_0_0_u1_11_11 manual__2023-03-28T14:30:49.312232+00:00 [queued]>
[2023-03-28 14:30:52,895] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-28 14:30:52,895] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-28 14:30:52,895] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-28 14:30:52,905] {taskinstance.py:1377} INFO - Executing <Task(DockerOperator): evco2_1_0_0_u1_11_11> on 2023-03-28 14:30:49.312232+00:00
[2023-03-28 14:30:52,911] {standard_task_runner.py:52} INFO - Started process 2680764 to run task
[2023-03-28 14:30:52,913] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'evco2_u1', 'evco2_1_0_0_u1_11_11', 'manual__2023-03-28T14:30:49.312232+00:00', '--job-id', '1443', '--raw', '--subdir', 'DAGS_FOLDER/evco2_u1.py', '--cfg-path', '/tmp/tmpjh0kpaui', '--error-file', '/tmp/tmpvefj2g2m']
[2023-03-28 14:30:52,914] {standard_task_runner.py:80} INFO - Job 1443: Subtask evco2_1_0_0_u1_11_11
[2023-03-28 14:30:52,947] {task_command.py:369} INFO - Running <TaskInstance: evco2_u1.evco2_1_0_0_u1_11_11 manual__2023-03-28T14:30:49.312232+00:00 [running]> on host bf048245faa1
[2023-03-28 14:30:52,996] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=evco2_u1
AIRFLOW_CTX_TASK_ID=evco2_1_0_0_u1_11_11
AIRFLOW_CTX_EXECUTION_DATE=2023-03-28T14:30:49.312232+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-28T14:30:49.312232+00:00
[2023-03-28 14:30:53,062] {docker.py:247} INFO - Starting docker container from image registry.gitlab.com/inlecom/lead/models/evco2:latest
[2023-03-28 14:30:54,220] {docker.py:308} INFO - Error in `dplyr::mutate()`:
ℹ In argument: `tco = Stock * energykwh`.
Caused by error:
! object 'energykwh' not found
Backtrace:
     ▆
  1. ├─global model(args$fp_factors, args$fp_consumption, args$outdir)
  2. │ ├─base::data.frame(...)
  3. │ └─global estimate_emission(fp_factors, fp_consumption)
  4. │   └─temp1 %>% dplyr::mutate(tco = Stock * energykwh)
  5. ├─dplyr::mutate(., tco = Stock * energykwh)
  6. ├─dplyr:::mutate.data.frame(., tco = Stock * energykwh)
  7. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  8. │   ├─base::withCallingHandlers(...)
  9. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 10. │     └─mask$eval_all_mutate(quo)
 11. │       └─dplyr (local) eval()
 12. └─base::.handleSimpleError(...)
 13.   └─dplyr (local) h(simpleError(msg, call))
 14.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
[2023-03-28 14:30:54,220] {docker.py:308} INFO - Execution halted
[2023-03-28 14:30:54,327] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/docker/operators/docker.py", line 387, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/docker/operators/docker.py", line 266, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/docker/operators/docker.py", line 313, in _run_image_with_mounts
    raise AirflowException(f'Docker container failed: {repr(result)} lines {joined_log_lines}')
airflow.exceptions.AirflowException: Docker container failed: {'Error': None, 'StatusCode': 1} lines Error in `dplyr::mutate()`:
ℹ In argument: `tco = Stock * energykwh`.
Caused by error:
! object 'energykwh' not found
Backtrace:
     ▆
  1. ├─global model(args$fp_factors, args$fp_consumption, args$outdir)
  2. │ ├─base::data.frame(...)
  3. │ └─global estimate_emission(fp_factors, fp_consumption)
  4. │   └─temp1 %>% dplyr::mutate(tco = Stock * energykwh)
  5. ├─dplyr::mutate(., tco = Stock * energykwh)
  6. ├─dplyr:::mutate.data.frame(., tco = Stock * energykwh)
  7. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  8. │   ├─base::withCallingHandlers(...)
  9. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 10. │     └─mask$eval_all_mutate(quo)
 11. │       └─dplyr (local) eval()
 12. └─base::.handleSimpleError(...)
 13.   └─dplyr (local) h(simpleError(msg, call))
 14.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
Execution halted
[2023-03-28 14:30:54,330] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=evco2_u1, task_id=evco2_1_0_0_u1_11_11, execution_date=20230328T143049, start_date=20230328T143052, end_date=20230328T143054
[2023-03-28 14:30:54,337] {standard_task_runner.py:92} ERROR - Failed to execute job 1443 for task evco2_1_0_0_u1_11_11 (Docker container failed: {'Error': None, 'StatusCode': 1} lines Error in `dplyr::mutate()`:
ℹ In argument: `tco = Stock * energykwh`.
Caused by error:
! object 'energykwh' not found
Backtrace:
     ▆
  1. ├─global model(args$fp_factors, args$fp_consumption, args$outdir)
  2. │ ├─base::data.frame(...)
  3. │ └─global estimate_emission(fp_factors, fp_consumption)
  4. │   └─temp1 %>% dplyr::mutate(tco = Stock * energykwh)
  5. ├─dplyr::mutate(., tco = Stock * energykwh)
  6. ├─dplyr:::mutate.data.frame(., tco = Stock * energykwh)
  7. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  8. │   ├─base::withCallingHandlers(...)
  9. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 10. │     └─mask$eval_all_mutate(quo)
 11. │       └─dplyr (local) eval()
 12. └─base::.handleSimpleError(...)
 13.   └─dplyr (local) h(simpleError(msg, call))
 14.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
Execution halted; 2680764)
[2023-03-28 14:30:54,368] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-28 14:30:54,396] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check

**Comment by andalexo** [comment]
This is an error due to erroneous input data.
On the platform there is a data asset called `EVCO2 demo` which you can download in order to see the format of the data.
https://platform.leadproject.eu/#/dashboard/asset-library
